# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-08 09:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0020_old_tree_cleanup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='js_megamenu_section', serialize=False, to='cms.CMSPlugin')),
                ('size', models.CharField(choices=[('2', '1/6'), ('3', '1/4'), ('4', '1/3'), ('6', '1/2')], default='2', max_length=1)),
                ('title', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
