# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-03 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('js_megamenu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='size',
            field=models.CharField(choices=[('2', '1/6'), ('3', '1/4'), ('4', '1/3'), ('6', '1/2'), ('8', '2/3')], default='2', max_length=1),
        ),
    ]
