# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-21 19:29
from __future__ import unicode_literals

from django.db import migrations
import djangocms_attributes_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('js_megamenu', '0002_auto_20190603_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='attributes',
            field=djangocms_attributes_field.fields.AttributesField(blank=True, default=dict, verbose_name='Attributes'),
        ),
    ]
